# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.161.0+26.3
# Check version on https://modrinth.com/mod/fabric-language-kotlin/versions
fabric_kotlin_version=1.14.1+kotlin.2.4.20
kotlin_version=2.4.0

# Mod Properties
mod_version=2.0.0+26.3
maven_group=io.urokhtor.minecraft
archives_base_name=container-tooltips

# Configuration
cloth_config_version=26.3.158
mod_menu_version=21.0.0
